/*******************************************************************************
 * @file descriptors.h
 * @brief USB descriptors header file.
 *******************************************************************************/

//=============================================================================
// inc/descriptors.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document. leave the sections
// inside the "$[...]" comment tags alone or they will be overwritten!
//=============================================================================
#ifndef __SILICON_LABS_DESCRIPTORS_H
#define __SILICON_LABS_DESCRIPTORS_H

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include "usb_includes.h"

#ifdef __cplusplus
extern "C"
{
#endif

// -------------------- USB Identification ------------------------------------
//
// **********
// NOTE: YOU MUST PROVIDE YOUR OWN USB VID/PID (below)
// **********
//
// Following are the definition of the USB VID and PID.  These are, by default,
// values that are assigned to Silicon Labs. These values are provided merely
// as an example. You may not use the Silicon Labs VID/PID values in your 
// product.  You must provide your own assigned VID and PID values.
//-----------------------------------------------------------------------------

// auto-generated string defines (Do not change)
// $[Vendor ID]
#define USB_VENDOR_ID                      htole16(0x45e)
// [Vendor ID]$

// $[Product ID]
#define USB_PRODUCT_ID                     htole16(0x2ea)
// [Product ID]$

// $[HID Report Descriptors]
// [HID Report Descriptors]$

// Global defines for descriptors
#define LANG_STRING   htole16( SLAB_USB_LANGUAGE )
#define HHL_MFR_STRING                             'H','a','n','d','H','e','l','d','L','e','g','e','n','d','\0'
#define HHL_MFR_SIZE                                15
#define HHL_SER_STRING   'H','A','X','\0'
#define HHL_SER_SIZE     4

// String externs
LANGID_STATIC_CONST_STRING_DESC( global_lang_descriptor[], LANG_STRING);
UTF16LE_PACKED_STATIC_CONST_STRING_DESC( global_mfr_descriptor[], HHL_MFR_STRING, HHL_MFR_SIZE);
UTF16LE_PACKED_STATIC_CONST_STRING_DESC( global_serial_descriptor[], HHL_SER_STRING, HHL_SER_SIZE);


#ifdef __cplusplus
}
#endif

#endif // __SILICON_LABS_DESCRIPTORS_H

