//=========================================================
// src/EFM8UB10F16G-B-QFN28_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------

// $[Generated Includes]
//#include "efm8_usb.h"
// [Generated Includes]$

#include "usb_includes.h"

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int
main (void)
{

  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();
  gamepadStatus = GAMEPAD_STATUS_NOCONNECT;

  while (1)
    {
// $[Generated Run-time code]
// [Generated Run-time code]$

      IE_EA = 0;
      SFRPAGE = I2CSLAVE0_PAGE;
      I2C0CN0 &= ~I2C0CN0_BUSY__BMASK;    // Clear BUSY bit
      I2C0CN0 |= I2C0FCN0_RFLSH__FLUSH | I2C0FCN0_TFLSH__FLUSH;
      IE_EA = 1;

        while (!rx_complete);             // New I2C data received?
        gamepadCmd();
        rx_complete = false;
    }
}
